### PR TITLE
additional_copy_path

### PR DESCRIPTION
**Pull request by jolexa**
When testing an ansible playbook, I was having to invent ways to get the test environment to include a directory, like a task dir or a vars dir. So, I wrote this to additionally copy a directory from CWD.

While this isn't the best solution, I feel like it will help some people. I welcome your comments. Thanks in advance!

### CODE REVIEW

**Comment by jolexa** [comment]
Even I found this not as robust as I like. One possible solution in `.kitchen.yml` is:

```
driver:
    name: vagrant
    synced_folders:
      - [".", "/vagrant", "create: true"]
```

**Comment by neillturner** [comment]
thanks for your comments. I am devops contractor so i work with different ttols depending on the contract. Currently busy doing puppet/AWS stuff so not much time to devote to ansible as i would like. Hopefully my next contract will involve ansible and i can push this code forward. currently i mostly relying on pull request from others. I am also working on windows winrm support for my kitchen-puppet plugin so when i have that working i should be able to port across to kitchen-ansible.

**Comment by trinitronx** [comment]
@neillturner:  Thanks for handling these pull requests!  I'm sure we all can understand that this is on the side of your desk for the moment.  I'm also finding myself with a lack of time to dedicate to implementing all the features I wanted to add.  However, it's a happy surprise to see some of them already in here like ansible-galaxy support, and some fixes to the script that installs ansible.

@jolexa:  Thanks for the contribution!  I too have been trying to figure out a good way to install test-fixtures and other files into the kitchen VM and also came across the vagrant driver's `synced_folders` solution.   At first glance my thought with this method is that it's not something that's at full feature-parity with other drivers.  However, your PR seems like it will definitely work with other drivers!

Now the only concern is whether we should try to keep kitchen-puppet and other test-kitchen provisioner gems in parity with kitchen-ansible.  I suppose my answer right now is "it doesn't matter for the moment".  However, I'm a big fan of keeping things in parity in general.

**Comment by trinitronx** [comment]
@jolexa: After [thinking about a similar issue][1] wondering if this directory name should be standardized as simply: `files`.  Or perhaps we should add more `prepare_foo_dir` methods as needed and just try to follow the [suggested repo directory layout convention][2] like we have been already (perhaps without realizing it :smile_cat:).

[1]: https://github.com/neillturner/kitchen-ansible/issues/10#issuecomment-73839288
[2]: http://docs.ansible.com/playbooks_best_practices.html#directory-layout

**Comment by jolexa** [comment]
no preference/opinion on that front since I ended up going with the synced folders route. For better or worse.

**Pull request merged**
