### PR TITLE
Install Busser rather than installing the entire Chef omnibus

### PR DESCRIPTION
**Pull request by mheap**
This has been tested on an Ubuntu guest machine and seems to work. 

My test machine installs ntpd and makes sure the service is running.

>        Finished in 0.09938 seconds (files took 0.3168 seconds to load)
       3 examples, 0 failures

### CODE REVIEW

**Comment by neillturner** [comment]
the issue to run busser is that you need ruby 1.9 of higher so reducing the install to busser only wont work as you need a ruby 19 installed.  

With test-kitchen 1.4.0 you just need a version of ruby 1.9 or higher and you can specify the path. 
not a problem with ubuntu as ruby 1.9 has been around for awhile.  Centos 6 come only with ruby 1.8.7 however you can install ruby 1.9 using the software collections: 
   https://digitalchild.info/centos-6-5-and-ruby1-9-3-via-software-collections/
   http://developerblog.redhat.com/2013/01/28/software-collections-on-red-hat-enterprise-linux/. 
Centos 7 does have ruby 1.9 of higher so the long term solution is to replace installing onimbus chef with ruby 19 or higher. Busser will install itself when you do a verify first time (well at least ibn kitchen 1.4).

**Comment by mheap** [comment]
Ah, I assumed it wouldn't be this simple but I figured opening a PR would get conversation going. I'll take a look at 1.9 on CentOS

**Comment by mheap** [comment]
Finally found some time to look into this. The PR is far from ready, but I've managed to get Ruby 1.9.3 installed via SCL.

We can't use the standard `scl enable ruby193` as that spawns a new shell which TestKitchen doesn't control. Instead, we just source the `enable` file to load ruby193 into the current session.

Later on, TestKitchen installs `busser-serverspec` which is out of scope of our call to `enable`. The paths in this script are hard coded to `/usr/bin/ruby` and `/usr/bin/gem`. To get around this, I've added symlinks to create these paths, and have added the ruby193 shared libraries to the system using ldconfig.

The PR still needs a lot of work on things like OS detection and whether we need to use SCL at all if the box is CentOS but already has Ruby >= 1.9, but it's a good starting point.

@neillturner Is this a route that you're happy to go down, or do you want to look at other options?

**Comment by neillturner** [comment]
what i was going to do was the following: 

1. make the chef install for busser more obvious
 add a new parameter 
 require_chef_for_busser default to false  and use this for the test instead of chef_url in install_busser.
NOTE: install_busser is mis-named it actually installs the busser pre-requisites. 

2. add option to install ruby for for busser
add a new parameter 
 require_ruby_for_busser default to true 
 this does a gem install ruby and ruby_devel

3. what to do for centos 6.
centos 6 has old version of ruby 1.8.7 while busser needs ruby 1.9. 
so either  we put out an error message and say you need to install chef or 
we install Ruby via SCL. 

sounds like you have done alot of that so if you push your code i can modify to the above or you can change you push or you can discuss further if you have a better idea -) 

let me know what you think

**Comment by mheap** [comment]
The `require_chef_for_busser` parameter would work, but I'm a fan of removing dead code as quickly as possible. I'd rather test the new busser dependencies code on as many machines as possible and remove the chef omnibus code completely.

I'm not following what option 2 would achieve. I'm not a ruby developer, so more details would be appreciated there.

RE: Option 3, If we can solve a problem for the user, I think we should do it. If we know how to install Ruby 1.9, why tell them that it's an issue? We should just install Ruby 1.9

**Comment by neillturner** [comment]
I used you code to add an option require_ruby_for busser. 
Can you you test this as i won't be able to test for a couple of days.

**Comment by neillturner** [comment]
The busser is installed by test-kitchen not this plugin. In kitchen 1.4.0 you can create your own bussers so we done want to install the busser gem, just ruby so that test-kitchen can install busser. 
 I prefer to leave old options as then we don't break folks code. -) 
so hence i have used your code to do Option 3 and install ruby 1.9 for centos 6. -)

**Comment by mheap** [comment]
Looks good to me. Closing this PR

**Pull request closed without merging**
