### PR TITLE
Changes to work on Amazon Linux.

### PR DESCRIPTION
**Pull request by rjosephwright**
Check for /etc/system-release as used by Amazon Linux. Install epel
repository only if it does not already exist, and explictly enable
epel when running yum.

### CODE REVIEW

**Comment by neillturner** [comment]
I think this change will break the install for non-amazon linux - ie centos. redhat. 
can we do it more like the kitchen-puppet code: 
 ie can we allow people to specify amazon as a platform 
and also try to determine if it is amazon and then do this code. 

in https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb
 look at the  def install_command from line 151

**Comment by rjosephwright** [comment]
It should work on rhel and centos if epel is being used as the repository. However, I probably shouldn't assume that everyone will use epel. I will work on a change more like what you suggest.

**Comment by neillturner** [comment]
your right epel should work but if it works without epel on centos and erdhat then its better to leave it out as it one less requirement. folks can then use ansible to add the epel if they need it on centos and redhat.

**Comment by neillturner** [comment]
install on amazon-linux works in kitchen-ansible 0.0.25
use the kitchen.yml option 
      enable_yum_epel: true

**Pull request closed without merging**
