### PR TITLE
handle symlinks in copied directories

### PR DESCRIPTION
**Pull request by benjamink**
Fix for symlinks inside roles directories as created specifically by [git-repo](https://code.google.com/p/git-repo/).  

#173

### CODE REVIEW

**Comment by neillturner** [comment]
Hey should the if be the other way so if copy_symlinks is true we do the cp -L command? 
default is false so we continue old behaviour of using FileUtils by default. 

         if config[:copy_symlinks]
           system("cp -LR #{roles} #{File.join(tmp_roles_dir, role_name)}")
         else
            FileUtils.cp_r(Dir.glob("#{roles}/*"), File.join(tmp_roles_dir, role_name))  
         end

**Comment by benjamink** [comment]
No because the `cp -LR` command is dereferencing symlinks (aka, when `copy_symlinks: false`) while the `FileUtils.cp_r` doesn't (aka, when `copy_symlinks: true`).

I ran into another problem with this, though.  Maybe you can think of an easy fix.  When the `.git/` directories are copied/dereferenced, the index files are mode 444 - read-only.  This works fine on initial converge, but on subsequent converges kitchen fails because it can't overwrite the files inside the guest.  

I'm starting to wonder if a better approach to this would be to outright exclude the `.git/` directories altogether.  Isn't this what you did in the kitchen-puppet provisioner?  Can we tell `FileUtils.cp_r` to exclude a list of file globs?

**Comment by neillturner** [comment]
you are right the 2 issues with copying files are symlinks and permissions. 
I agree it is better to ignore the directories if you don't need then 
i had two approaches: 
1. ignore_spec_fixtures  
which allowed the spec/features directory to be ignored 
2. ignored_paths_from_root
 which allowed extra paths to be ignored when copying from puppet repository 

yes we can do something similar 
just need to figure out the details. 
do with have an option 
ignore_role_git_directory
which will ignore all the .git directories in the roles. 
or do we get folks to enter   role\abc\.git  into a generic parameter.

**Comment by neillturner** [comment]
something like: 
FileUtils.cp_r(Dir.glob(File.join(roles, '*')).reject { |entry| entry =~ /.git$/ }, FileUtils.cp_r(Dir.glob("#{roles}/*"), File.join(tmp_roles_dir, role_name))) if config[:iignore_role_git_directory]
FileUtils.cp_r(Dir.glob("#{roles}/*"), File.join(tmp_roles_dir, role_name)) unless config[:ignore_role_git_directory]

**Comment by benjamink** [comment]
I'm not entirely following that logic, especially without the formatting.  Could you put that in context?  I think it's what I'm taking about, but not sure.

**Comment by neillturner** [comment]
try this using if else rather than functional programming. -)  

```
if config[:iignore_role_git_directory]
  FileUtils.cp_r(Dir.glob(File.join(roles, '*')).reject { |entry| entry =~ /.git$/ }, FileUtils.cp_r(Dir.glob("#{roles}/*"), File.join(tmp_roles_dir, role_name)))
else
  FileUtils.cp_r(Dir.glob("#{roles}/*"), File.join(tmp_roles_dir, role_name))
end
```

**Comment by benjamink** [comment]
I can try that.  Curious what that approach gains over the one I submitted in the last commit on my PR?  I thought my approach would be more "Ruby-esque".  Your code example still should be configurable with a variable though.

**Comment by neillturner** [comment]
this code rejects the directory that is .git 
  FileUtils.cp_r(Dir.glob(File.join(roles, '*')).reject { |entry| entry =~ /.git$/ }, FileUtils.cp_r(Dir.glob("#{roles}/*"), File.join(tmp_roles_dir, role_name)))
rather than your 
   system("cp -LR #{roles} #{File.join(tmp_roles_dir, role_name)}")
but i loked again now and you have new code with new parameter ignore_paths_from_root. 
I'm happy to merge this code if you have tested it and it works. Just confirm and i will merge.

**Comment by benjamink** [comment]
I added a rudimentary spec test to the code in my last commit.  The changes work for me as expected.  I can send debug output if you'd like.

**Comment by neillturner** [comment]
it fine i will merge and release today.

**Pull request merged**
