### PR TITLE
New: Ran Rubocop --auto-correct on everything. 

### PR DESCRIPTION
**Pull request by mheap**
Also made some manual fixes for guard clauses.

This doesn't solve all Rubocop issues, but it solves most of them. It solves
all whitespace issues, meaning that future PRs can be submitted safely without
worrying about conflicts

### CODE REVIEW

**Comment by mheap** [comment]
Working on the failures

**Comment by mheap** [comment]
@neillturner is this likely to be merged? If so I can start another branch based on this one, but don't want to do any work based on work that may be rejected

**Comment by neillturner** [comment]
sorry i missed this too busy creating my busser-ansblespec. Have a few other enhancements to put in and then i will release. push anything else you'd like to get into the product

**Comment by mheap** [comment]
No worries. I hadn't seen busser-ansiblespec. It's looking good!

There's no rush to release any changes I submit as they're all refactors and so they don't add/remove any functionality

**Comment by neillturner** [comment]
i appreciate you doing this. Had lots of contributions (which is great) but style is not that consistent.

**Pull request merged**
